name: helpeaze
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  flutter_riverpod: ^2.0.0-dev.9
  simple_animations: ^5.0.0+2
  font_awesome_flutter: ^10.2.1
  flutter_font_icons: ^2.2.5
  flutter_screenutil: ^5.5.4
  flutter_secure_storage: ^6.0.0
  flex_color_scheme: ^6.0.0
  fluttertoast: ^8.0.9
  flutter_native_splash: ^2.2.9
  flutter_snake_navigationbar: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg


  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  image: assets/icons/splash.png
  #background_image: assets/splash.png
  android_gravity: center

  color: "#42a5f5"
  fullscreen: false